name: Publish

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/nodejs.yml

  publish-client:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/

      - run: cd client && yarn install --immutable && yarn build

      - run: cd client && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

  publish-docker:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/gas-buddy/container-proxy:latest .

      - name: Push Docker image
        run: docker push ghcr.io/gas-buddy/container-proxy:latest
